import { Supplier } from '../../../core/models/supplier.model';

export const SUPPLIER_MOCK: Supplier[] = [
  {
    id: 'su-0001-0000-0000-000000000001',
    name: 'Importadora Automotriz del Oriente S.R.L.',
    description: 'Importadora mayorista de repuestos y autopartes para vehículos livianos y pesados. Distribución nacional desde Santa Cruz.',
    email: 'ventas@iaobolivia.com',
    address: 'Av. Banzer Km 7.5, Parque Industrial, Santa Cruz de la Sierra',
    state: 'ACTIVE',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-07-10'),
  },
  {
    id: 'su-0001-0000-0000-000000000002',
    name: 'Distribuidora de Lubricantes Petro Sur',
    description: 'Distribuidor autorizado de lubricantes Mobil, Shell y Castrol. Venta al por mayor y menor para talleres y flotas.',
    email: 'contacto@petrosur.bo',
    address: 'Calle Murillo 340, El Alto, La Paz',
    state: 'ACTIVE',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-08-05'),
  },
  {
    id: 'su-0001-0000-0000-000000000003',
    name: 'Herramientas Industriales Tecno-Tool',
    description: 'Importador y distribuidor de herramientas de taller: llaves, torquímetros, compresores y equipos de diagnóstico OBD.',
    email: 'info@tecnotool.com.bo',
    address: 'Av. Blanco Galindo Km 5, Cochabamba',
    state: 'ACTIVE',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-09-12'),
  },
  {
    id: 'su-0001-0000-0000-000000000004',
    name: 'Neumáticos y Llantas Rueda Libre',
    description: 'Distribuidor exclusivo de neumáticos Bridgestone, Firestone y Fate para vehículos de pasajeros, SUV y camiones.',
    email: 'pedidos@ruedalibresrl.com',
    address: 'Av. Argentina 1850, Santa Cruz de la Sierra',
    state: 'ACTIVE',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-09-28'),
  },
  {
    id: 'su-0001-0000-0000-000000000005',
    name: 'ElectroParts Bolivia',
    description: 'Especialistas en componentes eléctricos automotrices: baterías, alternadores, sensores y sistemas de encendido.',
    email: 'electroparts@gmail.com',
    address: 'Calle Esteban Arze 542, Cochabamba',
    state: 'ACTIVE',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-10-01'),
  },
  {
    id: 'su-0001-0000-0000-000000000006',
    name: 'Filtros y Repuestos Andinos',
    description: 'Distribuidora de filtros Bosch, Mann-Filter y Purflux. Amplio stock de filtros de aceite, aire y combustible.',
    email: 'ventas@filtrosandinos.bo',
    address: 'Zona Villa Fátima, La Paz',
    state: 'ACTIVE',
    createdAt: new Date('2024-03-18'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'su-0001-0000-0000-000000000007',
    name: 'Frenos y Suspensión del Sur S.A.',
    description: 'Importadora especializada en sistemas de frenos Monroe, Brembo y suspensión Gabriel. Garantía de fábrica en todos sus productos.',
    email: 'fsur@repuestosbol.com',
    address: 'Calle Ingavi 1230, Tarija',
    state: 'ACTIVE',
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-10-20'),
  },
  {
    id: 'su-0001-0000-0000-000000000008',
    name: 'Repuestos El Mecánico Express',
    description: 'Proveedor local de repuestos varios con entrega en 24 horas. Atención personalizada a talleres registrados.',
    email: null,
    address: 'Mercado Los Pozos, Local 215, Santa Cruz de la Sierra',
    state: 'INACTIVE',
    createdAt: new Date('2024-05-07'),
    updatedAt: new Date('2024-06-30'),
  },
];
